-- Tạo view chỉ xem được thông tin của chính bản thân cho NVCB
    CREATE OR REPLACE VIEW X_ADMIN.view_NVCB_NV AS 
    SELECT * FROM X_ADMIN.NHANVIEN where MaNV = SYS_CONTEXT('X_UNIVERSITY_CONTEXT','USER_NAME');
    -- Gán quyền SELECT, UPDATE(DT) trên view_NVCB cho NVCB và gán role NVCB cho tất cả các vai trò khác
    GRANT SELECT, UPDATE(DT) ON X_ADMIN.view_NVCB_NV TO XR_NVCB;
    GRANT XR_NVCB TO XR_TRGDV, XR_NVTCHC, XR_GV, XR_NVPDT, XR_NVPKT, XR_NVCTSV;


-- Tạo view quản lý nhân viên cho trưởng đơn vị và cấp quyền SELECT trên view này cho TRGDV
    CREATE OR REPLACE VIEW X_ADMIN.view_TRGDV_NV AS 
    SELECT MANV, HOTEN, PHAI, NGSINH, DT, VAITRO, MADV,
        DECODE(MANV,SYS_CONTEXT('X_UNIVERSITY_CONTEXT','USER_NAME'),LUONG,null) AS LUONG,
        DECODE(MANV,SYS_CONTEXT('X_UNIVERSITY_CONTEXT','USER_NAME'),PHUCAP,null) AS PHUCAP
    FROM NHANVIEN 
    WHERE MADV = (SELECT MADV FROM NHANVIEN WHERE MANV = SYS_CONTEXT('X_UNIVERSITY_CONTEXT','USER_NAME'));
    GRANT SELECT ON X_ADMIN.view_TRGDV_NV TO XR_TRGDV;
    -- Cấp toàn quyền trên bảng NHANVIEN cho NVTCHC
    GRANT SELECT, UPDATE, INSERT, DELETE ON NHANVIEN TO XR_NVTCHC;

COMMIT;
