ARCHIVE LOG LIST;
-- Tạo tablespace để test
-- vì em đã tạo tablespace rồi nên em sẽ không tạo lại nữa
    CREATE TABLESPACE RECOVERY_TEST DATAFILE 'RECOVERY_TEST.DBF'
    SIZE 10M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

    CREATE USER RMAN_TEST IDENTIFIED BY 123;
    GRANT CONNECT, RESOURCE TO RMAN_TEST;
    GRANT CREATE TABLE, CREATE SESSION TO RMAN_TEST;
    ALTER USER RMAN_TEST QUOTA UNLIMITED ON RECOVERY_TEST;
    COMMIT;

-- Tạo data để test
-- thêm dữ liệu vào tablespace này
    CREATE TABLE RMAN_TEST.DATA_TEST
    (
        ID NUMBER,
        NAME VARCHAR2(50),
        AGE NUMBER
    ) TABLESPACE RECOVERY_TEST;
    INSERT INTO RMAN_TEST.DATA_TEST (ID, NAME, AGE) VALUES (1, 'John Doe', 30);
    INSERT INTO RMAN_TEST.DATA_TEST (ID, NAME, AGE) VALUES (2, 'Jane Smith', 25);
    INSERT INTO RMAN_TEST.DATA_TEST (ID, NAME, AGE) VALUES (3, 'Alice Johnson', 28);
    INSERT INTO RMAN_TEST.DATA_TEST (ID, NAME, AGE) VALUES (4, 'Bob Brown', 35);
    INSERT INTO RMAN_TEST.DATA_TEST (ID, NAME, AGE) VALUES (5, 'Charlie Davis', 22);
    INSERT INTO RMAN_TEST.DATA_TEST (ID, NAME, AGE) VALUES (6, 'Diana Evans', 27);
    INSERT INTO RMAN_TEST.DATA_TEST (ID, NAME, AGE) VALUES (7, 'Ethan Foster', 31);
    INSERT INTO RMAN_TEST.DATA_TEST (ID, NAME, AGE) VALUES (8, 'Fiona Green', 29);
    INSERT INTO RMAN_TEST.DATA_TEST (ID, NAME, AGE) VALUES (9, 'George Harris', 33);
    INSERT INTO RMAN_TEST.DATA_TEST (ID, NAME, AGE) VALUES (10, 'Hannah Ivers', 26);
    INSERT INTO RMAN_TEST.DATA_TEST (ID, NAME, AGE) VALUES (11, 'Ian Johnson', 24);
    COMMIT;
-- Đóng tablespace
    ALTER TABLESPACE RECOVERY_TEST OFFLINE IMMEDIATE;
    STARTUP MOUNT;
-- Xóa datafile của tablespace để giả lập tình huống mất mát dữ liệu
    ALTER DATABASE DATAFILE 'RECOVERY_TEST.DBF' OFFLINE DROP;
-- Thực hiện phục hồi với RMAN
    -- RMAN> CONNECT TARGET /
    -- RMAN> RESTORE TABLESPACE RECOVERY_TEST;
    -- RMAN> RECOVER TABLESPACE RECOVERY_TEST;
-- Mở lại database
    ALTER DATABASE OPEN;
    ALTER TABLESPACE RECOVERY_TEST ONLINE;   

-- Két nối lại và truy vấn dữ liệu để kiểm tra kết quả phục hồi
    SELECT * FROM RMAN_TEST.DATA_TEST;