SELECT * FROM X_ADMIN.USER_ROLES;
SELECT * from X_ADMIN.SINHVIEN;
SELECT * from X_ADMIN.DANGKY;
SELECT * from X_ADMIN.MOMON;
SELECT * from X_ADMIN.HOCPHAN;
SELECT * from X_ADMIN.NHANVIEN;
SELECT * FROM X_ADMIN.DONVI;
SELECT * FROm X_ADMIN.VIEW_NVCB_NV;
SELECT * FROM X_ADMIN.THONGBAO;
SELECT * FROm X_ADMIN.VIEW_PDT_MOMON;

DECLARE
   username VARCHAR2(10);
    isSV INTEGER;
    isNVCB INTEGER;
    isAdmin INTEGER;
    isNVTCHC INTEGER;
BEGIN
   username := SYS_CONTEXT('X_UNIVERSITY_CONTEXT','USER_NAME');
   isSV := SYS_CONTEXT('X_UNIVERSITY_CONTEXT','IS_SV');
   isNVCB := SYS_CONTEXT('X_UNIVERSITY_CONTEXT','IS_NVCB');
   isAdmin := SYS_CONTEXT('X_UNIVERSITY_CONTEXT','IS_ADMIN');
   isNVTCHC := SYS_CONTEXT('X_UNIVERSITY_CONTEXT','IS_NVTCHC');
   DBMS_OUTPUT.PUT_LINE('username: ' || username);
   DBMS_OUTPUT.PUT_LINE('isSV: ' || isSV);
   DBMS_OUTPUT.PUT_LINE('isNVCB: ' || isNVCB);
   DBMS_OUTPUT.PUT_LINE('isAdmin: ' || isAdmin);
   DBMS_OUTPUT.PUT_LINE('isNVTCHC: ' || isNVTCHC);
END;
/
SELECT MaMM 
       FROM X_ADMIN.MOMON
       WHERE CURRENT_DATE - TRUNC(TO_DATE(NAM || '-' || 
          CASE HK WHEN 1 THEN '09' WHEN 2 THEN '01' WHEN 3 THEN '05' END, 'YYYY-MM')) 
          BETWEEN 0 AND 13;
      
COMMIT;

UPDATE X_ADMIN.DANGKY SET DIEMTH = 8
WHERE MASV= 'SV0001' AND MAMM = 'MM015';
